#:schema node_modules/wrangler/config-schema.json
name = "podcast-station"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "podcast-station-d1"
database_id = "421120a7-7228-43e1-a161-b7b5562db835"

[[r2_buckets]]
binding = "Bucket"
bucket_name = "podcast-station-r2"
